<?php

namespace directapi\common\enum\clients;


use directapi\components\Enum;

class ElementEnum extends Enum
{
    const CAMPAIGNS_TOTAL_PER_CLIENT = 'CAMPAIGNS_TOTAL_PER_CLIENT';
    const CAMPAIGNS_UNARCHIVED_PER_CLIENT = 'CAMPAIGNS_UNARCHIVED_PER_CLIENT';
    const ADGROUPS_TOTAL_PER_CAMPAIGN = 'ADGROUPS_TOTAL_PER_CAMPAIGN';
    const ADS_TOTAL_PER_ADGROUP = 'ADS_TOTAL_PER_ADGROUP';
    const KEYWORDS_TOTAL_PER_ADGROUP = 'KEYWORDS_TOTAL_PER_ADGROUP';
    const AD_EXTENSIONS_TOTAL = 'AD_EXTENSIONS_TOTAL';
    const STAT_REPORTS_TOTAL_IN_QUEUE = 'STAT_REPORTS_TOTAL_IN_QUEUE';
    const FORECAST_REPORTS_TOTAL_IN_QUEUE = 'FORECAST_REPORTS_TOTAL_IN_QUEUE';
    const WORDSTAT_REPORTS_TOTAL_IN_QUEUE = 'WORDSTAT_REPORTS_TOTAL_IN_QUEUE';
    const API_POINTS = 'API_POINTS';
}