<?php

namespace directapi\common\enum\clients;


use directapi\components\Enum;

class ElementEnum extends Enum
{
    public const CAMPAIGNS_TOTAL_PER_CLIENT = 'CAMPAIGNS_TOTAL_PER_CLIENT';
    public const CAMPAIGNS_UNARCHIVED_PER_CLIENT = 'CAMPAIGNS_UNARCHIVED_PER_CLIENT';
    public const ADGROUPS_TOTAL_PER_CAMPAIGN = 'ADGROUPS_TOTAL_PER_CAMPAIGN';
    public const ADS_TOTAL_PER_ADGROUP = 'ADS_TOTAL_PER_ADGROUP';
    public const KEYWORDS_TOTAL_PER_ADGROUP = 'KEYWORDS_TOTAL_PER_ADGROUP';
    public const AD_EXTENSIONS_TOTAL = 'AD_EXTENSIONS_TOTAL';
    public const STAT_REPORTS_TOTAL_IN_QUEUE = 'STAT_REPORTS_TOTAL_IN_QUEUE';
    public const FORECAST_REPORTS_TOTAL_IN_QUEUE = 'FORECAST_REPORTS_TOTAL_IN_QUEUE';
    public const WORDSTAT_REPORTS_TOTAL_IN_QUEUE = 'WORDSTAT_REPORTS_TOTAL_IN_QUEUE';
    public const API_POINTS = 'API_POINTS';
    public const GENERAL_DOMAIN_BLACKLIST_SIZE = 'GENERAL_DOMAIN_BLACKLIST_SIZE';
    public const VIDEO_DOMAIN_BLACKLIST_SIZE = 'VIDEO_DOMAIN_BLACKLIST_SIZE';

}